export const DOWNLOAD_FINISHED_CNT = 10;
export const COOKIE_JWT_TOKEN = 'mc_jwt_token';
export const JWT_USER_EXPIRE_TIME = '1d';
export const BASE64_PREFIX = ';base64,';
export const STOCK_ORDER_MAX_VOLUME = 49;
export const STOCK_ACCOUNT_MAX_VOLUME = 100;
export const STOCK_ACCOUNT_MAX_REMAIN_VOLUME = 51;
export const STOCK_INITIAL_MARGIN = 0.2;
export const ADMIN_MANUAL_OUTFLOW_METHOD = 'ADMIN_MANUAL_OUTFLOW_METHOD';
export const ADMIN_MANUAL_OUTFLOW_PROVIDER = 'ADMIN_MANUAL_OUTFLOW_PROVIDER';
export const ADMIN_MANUAL_OUTFLOW_UUID = 'ADMIN_MANUAL_OUTFLOW_UUID';

// 수수료 율
export const MARKET_FEE_RATE = 0.2;

export const SORT_TYPE = {
  ASC: 'ASC' as const,
  DESC: 'DESC' as const,
};

export const ADMIN_ROLE = {
  SUPER: 'SUPER', // 최고 관리자
  CUSTOMER: 'CUSTOMER', // 고객 관리
  EDITOR: 'EDITOR', // 홈페이지 관리
  COMMON: 'COMMON', // 기획
};

export const USAGE_HISTORY_TYPE = {
  MARKET: 'MARKET',
  STOCK_MATCH_BUY: 'STOCK_MATCH_BUY',
  PROMPT: 'PROMPT',
};

// ===================================== ACOUNT================================
export const ACCOUNT_HISTORY_TYPE = {
  POINT: 'POINT', // 포인트
  ASSET: 'ASSET', // 자산
};

export const ACCOUNT_HISTORY_STATUS = {
  NONE: 'NONE', // 기본 상태
  PENDING: 'PENDING', // 처리중
  CANCELED: 'CANCELED', // 취소
  UNCONFIRMED: 'UNCONFIRMED', // 미확인
  CONFIRMED: 'CONFIRMED', // 확인
};

export const ACCOUNT_HISTORY_LEDGER_TYPE = {
  DEPOSIT: 'DEPOSIT', // 입금
  WITHDRAW: 'WITHDRAW', // 출금
};

export const ACCOUNT_CURRENCY = {
  CL: 'CL', // CL
  OS: 'OS', // OS
  KRW: 'KRW', // KRW
};

// ===================================== PAYMENT================================
export const PAYMENT_HISTORY_STATUS = {
  READY: 'READY', // 결제대기
  PAID: 'PAID', // 결제완료
  CANCELED: 'CANCELED', // 결제취소
  OUTFLOW: 'OUTFLOW', // 정산 완료
  OUTFLOW_CANCELED: 'OUTFLOW_CANCELED', // 정산 취소
};

// ===================================== MARKET================================
export const MARKET_HISTORY_STATUS = {
  WAITING: 'WAITING',
  CANCELED: 'CANCELED',
  COMPLETED: 'COMPLETED',
  REFUNDED: 'REFUNDED',
};

// ===================================== STOCK ================================
export const STOCK_MESSAGE_TYPE = {
  BUY: 'BUY',
  SELL: 'SELL',
  MODIFY_BUY: 'MODIFY_BUY',
  MODIFY_SELL: 'MODIFY_SELL',
  CANCEL: 'CANCEL',
  DELETE: 'DELETE',
  HIDE_ITEM: 'HIDE_ITEM',
};

export const FASTBOOK_MODE = {
  CREATE: 'CREATE',
  MODIFY: 'MODIFY',
  CANCEL: 'CANCEL',
};

export const STOCK_ORDER_TYPE = {
  BUY: 'BUY',
  SELL: 'SELL',
};

export const STOCK_ORDER_STATUS = {
  WAIT: 'WAIT',
  CANCELED: 'CANCELED',
  COMPLETE: 'COMPLETE',
  HIDE: 'HIDE',
};

// ===================================== PROFILE ================================
export const OUTFLOW_HISTORY_TYPE = {
  REFUND: 'REFUND',
  SETTLEMENT: 'SETTLEMENT',
};

export const OUTFLOW_HISTORY_STATUS = {
  PENDING: 'PENDING',
  PROGRESS: 'PROGRESS',
  CONFIRMED: 'CONFIRMED',
  CANCELED: 'CANCELED',
};

// ------------------------------------- INFRA --------------------------------
export const AWS_SQS_GROUP_ID = {
  VIDEO_TRANSFORM: 'video_group_id',
  STOCK_MATCH: 'matching_group_id',
};

export const AWS_S3_BUCKET_PATH = {
  MARKET_ITEM_THUMBNAIL: 'images/thumbnail',
  RAW_VIDEO: 'videos/raw',
  TRANSFORMED_VIDEO: 'videos/transformed',
};

export const RESPONSE_CODE = {
  // Common
  SUCCESS: 0,

  // USER
  USER_NOT_FOUND: 1000,
  USER_ALREADY_EXIST: 1001,
  USER_IS_DELETED: 1002,
  USER_INVALID_PASSWORD: 1003,
  USER_CURRENT_PASSOWRD_NEW_PASSWORD_SAME: 1004,
  USER_BANK_ACCOUNT_NOT_MATCH: 1005,
  USER_SIGNIN_RETRIAL_COUNT_EXCEEDED: 1006,
  USER_INSUFFICIENT_CL: 1007,
  USER_IS_EXIST_VIDEO: 1008,
  USER_NOT_FOUND_WORKSPACE_KEYWORD: 1009,
  USER_DUPLICATE_KEYWORD: 1010,
  USER_BANK_ACCOUNT_FAILED: 1011,
  USER_SUPPORT_BUSINESS_EXIST: 1012,
  USER_SUPPORT_BUSINESS_NOT_EXIST: 1013,
  USER_SUPPORT_CUSTOMER_NOT_EXIST: 1014,

  // AUTH
  AUTH_INVALID_TOKEN: 2000,
  AUTH_EXPIRED_TOKEN: 2001,
  AUTH_NOT_FOUND: 2002,

  // ACCOUNT

  // OUTFLOW
  OUTFLOW_HISTORY_NOT_FOUND: 3000,
  OUTFLOW_CREATE_FAILED: 3001,
  OUTFLOW_EXPECTED_AMOUNT_NOT_MATCH: 3002,

  // VIDEO
  VIDEO_IS_DELETED: 6014,
  VIDEO_NOT_FOUND: 6000,
  VIDEO_NOT_OWNER: 6001,

  // PAYMENT
  PAYMENT_INVALID_BANK_ACCOUNT: 7000,
  PAYMENT_PREPARE_FAILED: 7001,
  PAYMENT_COMPLETE_FAILED: 7002,
  PAYMENT_REFUND_FAILED: 7003,
  PAYMENT_ERROR_CREATE: 7004,

  // MARKET
  MARKET_NOT_FOUND: 8000,
  MARKET_ALREADY_EXIST: 8001,
  MARKET_INVALID_THUMBNAIL_FORMAT: 8002,
  MARKET_ITEM_NOT_OWNER: 8003,
  MARKET_PURCHASE_FAILED: 8004,
  MARKET_ALREADY_LIKE: 8005,
  MARKET_NOT_LIKE: 8006,
  MARKET_CART_CREATE_FAILED: 8007,
  MARKET_CART_NOT_FOUND: 8008,
  MARKET_LIKE_NOT_FOUND: 8009,
  MARKET_NOT_ACTIVE: 8010,
  MARKET_ALREADY_EXIST_SHOW: 8011,
  MARKET_ALREADY_EXIST_NOT_SHOW: 8012,
  MARKET_ITEM_NOT_DELETED: 8013,

  // STOCK
  STOCK_ITEM_NOT_FOUND: 9000,
  STOCK_ACCOUNT_GREATER_THAN_ZERO: 9001,
  STOCK_CREATE_FAILED: 9002,
  STOCK_ACCOUNT_NOT_FOUND: 9003,
  STOCK_ACCOUNT_INSUFFICIENT_VOLUME: 9004,
  STOCK_MATCHING_INVAILD_PARAMETER: 9005,
  STOCK_MATCHING_ERROR: 9006,
  STOCK_ORDER_NOT_FOUND: 9007,
  STOCK_ORDER_NOT_AVAILABLE: 9008,
  STOCK_ORDER_NO_CHANGE: 9009,
  STOCK_OWNER_ACCOUNT_NOT_FOUND: 9010,
  STOCK_OWNER_NOT_ALLOWED: 9011,
  STOCK_OWNER_TOO_MUCH_VOLUME: 9012,
  STOCK_ORDER_MAX_VOLUME: 9013,
  STOCK_ACCOUNT_ALREADY_EXIST: 9014,
  STOCK_ITEM_NOT_OWNER: 9015,
  STOCK_ACCOUNT_NOT_MAX_VOLUME: 9016,
  STOCK_ITEM_NOT_DELETED: 9017,
  STOCK_SELL_OVER_VOLUME: 9018,
  STOCK_ORDER_CANCEL_NOT_CREATED: 9019,
  STOCK_ORDER_CANCEL_NOT_FOUND: 9020,

  // ACCOUNT
  ACCOUNT_NOT_FOUND: 9100,
  ACCOUNT_ALREADY_EXIST: 9101,
  ACCOUNT_INSUFFICIENT_BALANCE: 9102,
  ACCOUNT_GREATER_THAN_ZERO: 9103,

  // SERVER ERROR - MESSAGE QUEUE
  MESSAGE_QUEUE_ERROR: 9000,
  MESSAGE_QUEUE_VIDEO_ERROR: 9001,

  // SERVER ERROR - DB
  DB_ERROR: 9200,

  // SERVER ERROR - AWS
  AWS_S3_UPLOAD_ERROR: 9300,
  AWS_SES_EMAIL_SEND_ERROR: 9301,

  // SERVER ERROR - LOGIC
  INVALID_PARAMETER: 9800,
  INTERNAL_SERVER_ERROR: 9999,
};

export const STOCK_EVENT = {
  FAST_BOOK: 'event-fastbook',
  MATCH: 'event-match',
  HIDE_FAST_BOOK: 'event-hide-fastbook',
};

export const STOCK_ORDER_CANCEL_TYPE = {
  BUYER_CANCEL: 'BUYER_CANCEL' as const,
  SELLER_CANCEL: 'SELLER_CANCEL' as const,
  SELLER_DELETE: 'SELLER_DELETE' as const,
  ADMIN_DELETE: 'ADMIN_DELETE' as const,
};

export const SUPPORT_STATUS = {
  PENDING: 'PENDING',
  PROGRESS: 'PROGRESS',
  CONFIRMED: 'CONFIRMED',
  CANCELED: 'CANCELED',
};
